### PR TITLE
fix(Hyundai USA): corrected odometer readings

### LINKED ISSUE #177: No odometer entity for Hyundai Santa Fe 2020
**Region and Brand of car**
USA, Hyundai Santa Fe 2020

**Describe the bug**
There is no odometer entity for my vehicle. 

**Expected behavior**
Odometer entity shows car's mileage. 

**Screenshots**
image

### PR DESCRIPTION
**Pull request by cdnninja**
Closes #177

### CODE REVIEW

**Comment by cdnninja** [comment]
@tucknology and @rappazzo could either of you test this for me? I am coding blind since I don't have a USA Hyundai.  Ideally would like this sit in one of your systems for atleast 24 hours since it increases API calls so want to make sure it doesn't max out the API.

**Comment by rappazzo** [comment]
Yeah, I could do that. I haven't figured out how to run a revision not on master yet.... How do I do that?

**Comment by cdnninja** [comment]
I like to use the add on samba share if using a supervised version of home assistant.  Once setup I can browse and drag and drop the files I need.  Restarting HA after to make the changes take effect.

**Comment by rappazzo** [comment]
I just copied `HyundaiBlueLinkAPIUSA.py` via samba into the kia_uvo dir on my HA instance and restarted.  There was a problem somewhere, as I got this in the log:

> 2021-12-03 09:13:20 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry <<redacted-email-address>> for kia_uvo

I am going to revert to make sure it isn't a temporary issue

**Comment by rappazzo** [comment]
Commenting out that logger line fixes it, and now I can see the odometer:
https://github.com/fuatakgun/kia_uvo/compare/master...rappazzo:odometer?expand=1

**Comment by cdnninja** [comment]
Are you able to retest?  I have corrected that line.

**Comment by rappazzo** [comment]
I am retesting with my version.  I will put yours in shortly

**Comment by rappazzo** [comment]
At this point your code has been running without any trouble for 24 hours.  The results are accurate.  My inclination is to merge this to master, and keep an eye on the queries separately.

**Pull request merged**
