### PR TITLE
fix: Corrected remote start types

### PR DESCRIPTION
**Pull request by cdnninja**

### CODE REVIEW

**Comment by dahlb** [comment]
seems it would be cleaner to move this logic into the CA implementation of start_climate to call it's ev method internally if engine is ev

**Comment by cdnninja** [comment]
If so I need to pass engine type into the API as the API isn't aware of engine type. I actually did this in a previous version but removed that type of logic as I have to decode and store engine type in both vehicle and api.   Or pass it into the start call.  Open to suggestions.

**Comment by dahlb** [comment]
I haven't used those functions yet but based on initially look, with this and some hacks to track current version of vehicle maybe these or at least some of the api fuctions would benefit from adding vehicle object to signatures

**Comment by cdnninja** [comment]
I am merging this to get it fixed as a temp fix.    @fuatakgun  is going to put some time into how to refactor some of this.  We are hitting issues with different APIs needing different things.

**Pull request merged**
