### PR TITLE
refactor: Switch to remote API and rewrite of code

### PR DESCRIPTION
**Pull request by cdnninja**
BREAKING CHANGE: 
New API and rewrite.

### CODE REVIEW

**Comment by fuatakgun** [comment]
should we chase this or leave this?

**Comment by cdnninja** [comment]
Leaving it for now. If I can get multicar working with it we could continue but don’t want to limit either side.

**Comment by cdnninja** [comment]
@rappazzo  Any chance you could test this PR for us for Hyundai USA? I suspect it has issues we need to resolve in our new API.

**Comment by rappazzo** [comment]
I'll put it in today and run it over the weekend

**Comment by cdnninja** [comment]
Yes that is correct.  Please read the warnings here: #219.

**Comment by rappazzo** [comment]
Seems to be missing a dependency
```
Logger: homeassistant.util.package
Source: util/package.py:100
First occurred: 8:53:05 AM (3 occurrences)
Last logged: 8:53:31 AM

Unable to install package hyundai_kia_connect_api==10.18.15: ERROR: Could not find a version that satisfies the requirement hyundai_kia_connect_api==10.18.15 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.6.0, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.8.0, 1.8.1, 1.8.2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.12.0, 1.12.1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.17.1, 1.17.3, 1.18.7, 1.18.8, 1.18.10, 1.18.11, 1.18.12, 1.18.13, 1.18.14, 1.18.15) ERROR: No matching distribution found for hyundai_kia_connect_api==10.18.15 WARNING: You are using pip version 20.2.4; however, version 21.3.1 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
```
To install, (via samba) I moved the contents of `config/custom_components/kia_uvo` to a backup location, and then copied the files from `https://github.com/fuatakgun/kia_uvo.git:externalAPI` to that dir.  New contents:
```
❯❯ ls custom_components/kia_uvo | head -n 1000
__init__.py
binary_sensor.py
config_flow.py
const.py
coordinator.py
entity.py
manifest.json
sensor.py
strings.json
translations
```

**Comment by cdnninja** [comment]
Typo in requirements on my part when I bumped it recently.   I also just made some larger changes to align it back to the current core implementation.

**Comment by rappazzo** [comment]
New errors: ```
Error setting up entry <my-email-address> for kia_uvo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/kia_uvo/__init__.py", line 24, in async_setup_entry
    coordinator = HyundaiKiaConnectDataUpdateCoordinator(hass, config_entry)
  File "/config/custom_components/kia_uvo/coordinator.py", line 41, in __init__
    self.vehicle_manager = VehicleManager(
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 37, in __init__
    self.api: ApiImpl = self.get_implementation_by_region_brand(
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 99, in get_implementation_by_region_brand
    return HyundaiBlueLinkAPIUSA(region, brand)
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 83, in __init__
    "username": self.username,
AttributeError: 'HyundaiBlueLinkAPIUSA' object has no attribute 'username'```

**Comment by cdnninja** [comment]
This is the exact sort of testing needed for this brand. Thank you!  I have updated the API so you can either pull a new copy of the manifest file or edit the file to show 1.18.16.

**Comment by rappazzo** [comment]
```
Unexpected error fetching kia_uvo data: 'Vehicle' object has no attribute 'vin'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/kia_uvo/coordinator.py", line 80, in _async_update_data
    await self.async_update_all()
  File "/config/custom_components/kia_uvo/coordinator.py", line 89, in async_update_all
    await self.async_check_and_refresh_token()
  File "/config/custom_components/kia_uvo/coordinator.py", line 104, in async_check_and_refresh_token
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 85, in check_and_refresh_token
    self.initialize()
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 50, in initialize
    self.update_all_vehicles_with_cached_state()
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 57, in update_all_vehicles_with_cached_state
    self.update_vehicle_with_cached_state(self.get_vehicle(vehicle_id))
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 60, in update_vehicle_with_cached_state
    self.api.update_vehicle_with_cached_state(self.token, vehicle)
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 164, in update_vehicle_with_cached_state
    state = self._get_cached_vehicle_state(token, vehicle)
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 126, in _get_cached_vehicle_state
    headers["vin"] = vehicle.vin
AttributeError: 'Vehicle' object has no attribute 'vin'
```

**Comment by cdnninja** [comment]
1.8.17 should solve that next one.

**Comment by rappazzo** [comment]
```
Unexpected error fetching kia_uvo data: can't compare offset-naive and offset-aware datetimes
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/kia_uvo/coordinator.py", line 80, in _async_update_data
    await self.async_update_all()
  File "/config/custom_components/kia_uvo/coordinator.py", line 89, in async_update_all
    await self.async_check_and_refresh_token()
  File "/config/custom_components/kia_uvo/coordinator.py", line 104, in async_check_and_refresh_token
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 86, in check_and_refresh_token
    if self.token.valid_until <= dt.datetime.now(pytz.utc):
TypeError: can't compare offset-naive and offset-aware datetimes
```

**Comment by cdnninja** [comment]
1.18.18 may resolve this.  Typically this is a time format issue.   This does mean it has already logged in successfully which is progress.

**Comment by rappazzo** [comment]
```
Unexpected error fetching kia_uvo data: type object 'datetime.datetime' has no attribute 'timedelta'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/kia_uvo/coordinator.py", line 80, in _async_update_data
    await self.async_update_all()
  File "/config/custom_components/kia_uvo/coordinator.py", line 89, in async_update_all
    await self.async_check_and_refresh_token()
  File "/config/custom_components/kia_uvo/coordinator.py", line 104, in async_check_and_refresh_token
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 85, in check_and_refresh_token
    self.initialize()
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 45, in initialize
    self.token: Token = self.api.login(self.username, self.password)
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 108, in login
    valid_until = (datetime.now(pytz.utc) + datetime.timedelta(seconds=expires_in))
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
```

**Comment by cdnninja** [comment]
Thanks for sticking with this.  Really appreciate it.  Unfortunately I don't have a way to access a USA car. 

Next is: 1.19.1

**Comment by rappazzo** [comment]
It's not a problem, I'm happy to help when I can.  
```
Setup failed for kia_uvo: unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 181, in _async_setup_component
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 522, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/kia_uvo/__init__.py", line 15, in <module>
    from .coordinator import HyundaiKiaConnectDataUpdateCoordinator
  File "/config/custom_components/kia_uvo/coordinator.py", line 7, in <module>
    from hyundai_kia_connect_api import VehicleManager
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/__init__.py", line 4, in <module>
    from .HyundaiBlueLinkAPIUSA import HyundaiBlueLinkAPIUSA
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 40, in <module>
    class HyundaiBlueLinkAPIUSA(ApiImpl):
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 43, in HyundaiBlueLinkAPIUSA
    last_loc_timestamp = dt.now() - dt.timedelta(hours=3)
AttributeError: module 'datetime' has no attribute 'now'
```

**Comment by cdnninja** [comment]
1.19.2

**Comment by rappazzo** [comment]
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/kia_uvo/__init__.py", line 24, in async_setup_entry
    coordinator = HyundaiKiaConnectDataUpdateCoordinator(hass, config_entry)
  File "/config/custom_components/kia_uvo/coordinator.py", line 41, in __init__
    self.vehicle_manager = VehicleManager(
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 37, in __init__
    self.api: ApiImpl = self.get_implementation_by_region_brand(
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 99, in get_implementation_by_region_brand
    return HyundaiBlueLinkAPIUSA(region, brand)
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 57, in __init__
    dt.fromtimestamp(ts) - dt.utcfromtimestamp(ts)
AttributeError: module 'datetime' has no attribute 'fromtimestamp'
```

**Comment by cdnninja** [comment]
1.19.3

**Comment by rappazzo** [comment]
```
Unexpected error fetching kia_uvo data: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/kia_uvo/coordinator.py", line 81, in _async_update_data
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 67, in check_and_force_update_vehicles
    f"time diff - {(started_at_utc - vehicle.last_updated_at).total_seconds()}"
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
```

**Comment by cdnninja** [comment]
Hopefully getting close.   Added the last update commands needed for it in 1.19.4.  

This past error occurs in the refresh of the data so past login issues at this point which is good.

**Comment by rappazzo** [comment]
needs to import `re`
```
Unexpected error fetching kia_uvo data: name 're' is not defined
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/kia_uvo/coordinator.py", line 80, in _async_update_data
    await self.async_update_all()
  File "/config/custom_components/kia_uvo/coordinator.py", line 89, in async_update_all
    await self.async_check_and_refresh_token()
  File "/config/custom_components/kia_uvo/coordinator.py", line 104, in async_check_and_refresh_token
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 85, in check_and_refresh_token
    self.initialize()
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 50, in initialize
    self.update_all_vehicles_with_cached_state()
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 57, in update_all_vehicles_with_cached_state
    self.update_vehicle_with_cached_state(self.get_vehicle(vehicle_id))
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 60, in update_vehicle_with_cached_state
    self.api.update_vehicle_with_cached_state(self.token, vehicle)
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 163, in update_vehicle_with_cached_state
    vehicle.last_updated_at = self.get_last_updated_at(
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 462, in get_last_updated_at
    m = re.match(r"(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})", value)
NameError: name 're' is not defined
```

**Comment by cdnninja** [comment]
10.19.5

**Comment by rappazzo** [comment]
```
Unexpected error fetching kia_uvo data: 'HyundaiBlueLinkAPIUSA' object has no attribute 'force_refresh_vehicle_state'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/kia_uvo/coordinator.py", line 81, in _async_update_data
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 72, in check_and_force_update_vehicles
    self.force_refresh_vehicle_state(vehicle)
  File "/usr/local/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 81, in force_refresh_vehicle_state
    self.api.force_refresh_vehicle_state(self.token, vehicle)
AttributeError: 'HyundaiBlueLinkAPIUSA' object has no attribute 'force_refresh_vehicle_state'
```

**Comment by cdnninja** [comment]
1.19.5 stubs out that.  It looks like for some reason the Hyundai USA implementation never had force refresh implemented.  At a future time we will need to look into how to call that.

**Comment by rappazzo** [comment]
Looks like it's working now.

**Comment by cdnninja** [comment]
Awesome!  What sensors are missing that you had before and want?   Data logs will help with that too but essentially mapping is done here:https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/9c846174d64cf63ef755feb47e72997b2ff7706d/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py#L162-L278

And then we create the sensor in the repo you provided if it isn't already.

**Comment by rappazzo** [comment]
I think the only sensor that I am missing from before that I care about is the odometer.  The Hyundai app provides actual tire pressure but that wasn't in the previous version (was just OK/Not OK).

**Comment by cdnninja** [comment]
If it is in the app it should be an option for us.  I can take a look at adding it unless something you want to take one!  I will work on those missing data points in the next few days.

**Comment by cdnninja** [comment]
1.20.0 adds the required odometer call.  It does the prep work for location as well.  Currently location doesn't have an entity created for any region in this new version.   Hope to have that soon though.  I am assuming it will cause an error since I am coding blind and new to this.

**Review by VincentCryptoGodfather52 — APPROVED** [review]

**Pull request closed without merging**
