### PR TITLE
fix(USA Hyundai): Allow weaker ciphers since Hyundai uses these

### PR DESCRIPTION
**Pull request by cdnninja**
Leaving in draft as this only does login right now.

### CODE REVIEW

**Comment by fuatakgun** [comment]
I suggest to do this as a fallback, first try normal more secure way, then on exception, use this less secure way?

**Comment by cdnninja** [comment]
> I suggest to do this as a fallback, first try normal more secure way, then on exception, use this less secure way?

If the server side supports higher I believe it will negotiate up to that.   Other option is I try using a higher cipher default and fall back to lower but that is the same as negotiating the cipher.

**Comment by cdnninja** [comment]
@fuatakgun ready for review as this solves the SSL error on newer version of ubuntu.

**Comment by cdnninja** [comment]
@fuatakgun I reverted the name.  When brackets are used it titles it like this: https://github.com/fuatakgun/kia_uvo/releases/tag/v1.2.4  I do need to watch case in that example.

**Pull request merged**
