### PR TITLE
feat(US Kia): Added miles until next service information

### PR DESCRIPTION
**Pull request by nprez83**
Update API request to download maintenance information and added it to vehicle_data to be returned as a sensor entity (sensor is already defined in sensor.py, variable just needed to be defined within KiaUvoAPIUSA file).

### CODE REVIEW

**Comment by cdnninja** [comment]
Awesome! Thank you for the contribution!   With this change do you see nextservice sensor?

**Comment by nprez83** [comment]
> Awesome! Thank you for the contribution! With this change do you see nextservice sensor in testing?

Indeed. With those changes, the nextservice entity sensor is loaded automatically, because it was already defined in the sensors.py file, so all we needed to do was pull the info in the API request, and then return it. Now there are 24 entities linked to the device, instead of 23 previously.

**Comment by cdnninja** [comment]
Awesome.  I think in CA we have a last service sensor too that you could map.  In the meantime I will merge.  Thanks again! Releases occur wednesday and weekends so until that time it will need to be updated to "latest" to have this.

**Comment by nprez83** [comment]
Awesome, thanks. I just looked at the log, and it looks like all the maintenance info I'm getting is the schedule and miles till next service (see below). I think @dahlb is using the odometer reading, appending it to the maintenance array, and indexing over that to figure out the last and next service, which is pretty clever. TBH, I'm satisfied just having the miles till next service, which can be used to trigger alerts. Thanks again!

`"maintenance":{"nextServiceMile":3112.5996,"maintenanceSchedule":[7500,15000,22500,30000,37500,45000,52500,60000,67500,75000,82500,90000,97500,105000,112500]}`

**Pull request merged**
